baseURL: "https://nicktackes.com/"
languageCode: en-us
title: Nick Tackes

Params:
  sidebar:
    img: "/img/NTprofile3.png"
    menu: ["about", "research", "teaching", "cv"]
    landing: "about"

  about: |
    I am an ethnographer of religion in South Asia, with a focus on the intersection of Hinduism, health, media, and the environment.

    My research explores how large-scale religious institutions intervene in consumer culture in order to provide solutions to modern societal problems.

  social:
    - URL: mailto:jtackesiii@gmail.edu
      icon: fas fa-envelope
    - URL: https://columbia.academia.edu/NickTackes/
      icon: ai ai-academia
    - URL: https://github.com/jtackesiii
      icon: fab fa-github
    - URL: https://linkedin.com/in/NickTackes
      icon: fab fa-linkedin

  credits:
    This site is built on [Hugo](https://gohugo.io),
     hosted on [Github](https://github.com), and
    served on [Netlify](https://netlify.com). Icons
    are by [Fontawesome](https://fontawesome.com) and
    [Academicons](https://jpswalsh.github.io/academicons).

  teaching:
    description:
      I am currently teaching
      "Religions of India" in New York University's Religion
      Department.
    link: https://as.nyu.edu/religiousstudies/courses/religions-of-india.html
