# Site settings
baseurl = ""
languageCode = "en-us"
title = "Classroom"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Nick Tackes"
    description = "PhD Student, Columbia University"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Nick Tackes"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Classroom"
        subtitle = "Sample site for a web-interactive course"


    [params.about]
        title = "About"
        description = "This is a sample site for a web-interactive course."


    [params.timeline]
        title = "Timeline"
        description = "This is a sample timeline for use in a course"


    [params.footer]
        copyright = "(c) 2018 Nick Tackes"

        [params.footer.location]
            title = ""
            # Postal address (add as many lines as necessary)
            address = ["", "", ""]

        [params.footer.social]
            title = ""
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link = "//facebook.com"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com"


        [params.footer.credits]
            title = ""
            text = ""
