baseURL: "https://nicktackes.com/"
languageCode: en-us
title: Nick Tackes

Params:
  sidebar:
    img: "/img/NTprofile3.png"
    menu: ["about", "research", "teaching", "cv"]
    landing: "about"

  about:
    I am an ethnographer of healing and religion in South Asia.
    My dissertation project is an investigation of the Gayatri
    Pariwar and the Brahma Kumaris, two Hindu-adjacent religious
    institutions whose members anticipate the imminent end of the
    world. Rather than retreat from society, however, these groups
    continue to engage their surrounding communities in attempts to
    provide innovative solutions to contemporary societal problems.
    My research attends to the branded goods, services, service
    projects, and ritual engagements that constitute their
    preparations for the end of this era and the golden age they
    believe will succeed it.

  social:
    - URL: https://columbia.academia.edu/NickTackes/
      icon: ai ai-academia
    - URL: https://github.com/jtackesiii
      icon: fa-github fa-lg
    - URL: https://linkedin.com/in/NickTackes
      icon: fa-linkedin

  teaching:
    description:
      During the spring 2022 semester, I will be teaching
      "Religions of India" in New York University's Religion
      Department.
    link: https://as.nyu.edu/religiousstudies/courses/religions-of-india.html
