# Site settings
baseurl = "https://nicktackes.com/"
languageCode = "en-us"
title = "Nick Tackes"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.

    name = "Nick Tackes"
    description = "Religion Department, Columbia University"
    email = "jnt2127@columbia.edu"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Nick Tackes"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "NTprofile2.jpg"
        name = "Nick Tackes"
        department = "Religion Department"
        university = "Columbia University"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Research"

        [params.portfolio.modal]
            link = "Link"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        description = "I am an ethnographer of healing and religion in South Asia. My dissertation project is an investigation of *care products*, a term I use to describe a subset of goods, services, and service projects offered by two Hindu institutions in Mathura, India. My research will determine for which reasons, by which means, and in which ways Indians incorporate these care products into their lives. To this end, I work between Religion and Medical Anthropology."

    [params.CV]
        title= "C.V."

        [params.CV.button]
            text = "Download CV"
            src = "/documents/Nick_Tackes.pdf"
            icon = "download"


    [params.contact]
        title = "Contact"
        link = "mailto:jnt2127@columbia.edu"


    [params.footer]
        copyright = "(c) 2020 Nick Tackes"

        [params.footer.location]
            title = ""
            # Postal address (add as many lines as necessary)
            address = ["", "", ""]

        [params.footer.social]
            title = ""
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "ai ai-academia"
                link=  "//columbia.academia.edu/NickTackes/"

            [[params.footer.social.networks]]
                icon = "fa-github fa-lg"
                link=  "//github.com/jtackesiii"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com/in/NickTackes/"

        [params.footer.credits]
            title = ""
            text = ""
